### ISSUE TITLE
Windows send to R console error

### ISSUE THREAD

**Issue by ChrisBern** [randy3k/SendTextPlus#33]
Hi,

Thank you very much for providing R-Box and SendTextPlus! 
Everything worked perfect for me, until I had to reinstall Windows 7 on my laptop a few days ago. Now that I installed ST3 with R-Box and SendTextPlus, I can not send code to the R console anymore. I have no clue why (sorry, I'm a just some stupid end-user...). The error messages are 1.)  

> Traceback (most recent call last):
  File "C:\opt\SublimeText3\sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "commands in C:\[...]\AppData\Roaming\Sublime Text 3\Installed Packages\SendTextPlus.sublime-package", line 84, in run
  File "textsender in C:\[...]\AppData\Roaming\Sublime Text 3\Installed Packages\SendTextPlus.sublime-package", line 45, in send_text
  File "textsender in C:\[...]\AppData\Roaming\Sublime Text 3\Installed Packages\SendTextPlus.sublime-package", line 300, in _dispatch_r64_windows
  File "textsender in C:\[...]\AppData\Roaming\Sublime Text 3\Installed Packages\SendTextPlus.sublime-package", line 277, in execute_ahk_script
  File "./subprocess.py", line 576, in check_output
  File "./subprocess.py", line 789, in __init__
  File "./subprocess.py", line 988, in _get_handles
  File "./subprocess.py", line 1038, in _make_inheritable
OSError: [WinError 6] The handle is invalid

and 2.)

> reloading Packages/User/SendText+.sublime-settings
warning: mnemonic r not found in menu caption R-Box

R is in the system PATH. And I chose R64 as prog...

Thank you for helping and sorry if this was some trivial issue!

**Comment by ChrisBern** [comment]
Including Rtools in the system PATH solved the problem...
Sorry for that.

**Comment by randy3k** [comment]
it is odd, it should has nothing to do with Rtools....

**Comment by ChrisBern** [comment]
I don't know - I tried to build a package and gcc gave compilation error status 127. 
So, after adding Rtools to the system PATH, I thought I'd give it another go with sendtextplus...
Might it be one of the commands that come with Rtools that fixed it?

**Comment by ChrisBern** [comment]
I'm really sorry, this is driving me crazy. Now I have the error back again...
I can not reproduce what might have changed since yesterday.
Can I provide any more information that might help solving the problem?
