### ISSUE TITLE
SendTextPlus fails to send commands to iTerm

### ISSUE THREAD

**Issue by NM-Clio** [randy3k/SendTextPlus#7]
I can't seem to have SendTextPlus send anything to iTerm. This is my SendTextPlus' user settings:    
```json
{
    // path to tmux and screen (linux/mac)
    "tmux" : "tmux",
    "screen" : "screen",

    // syntax settings
    "r" :
    {
        "prog" : "iTerm",
        "block" : true,
        "auto_advance" : true
    },
    "python" :
    {
        "prog" : "iTerm",
        "ipython" : true,
        "block" : true,
        "auto_advance" : true
    },
    "ruby" :
    {
        "prog" : "iTerm",
        "block" : true,
        "auto_advance" : true
    },
    "julia" :
    {
        "prog" : "iTerm",
        "block" : true,
        "auto_advance" : true
    },

    // default settings
    "default":
    {
        "osx" : {
            "prog" : "iTerm",
            "auto_advance" : true
        },
        "linux" : {
            "prog" : "tmux",
            "auto_advance" : true
        },
        "windows" : {
            "prog" : "PowerShell",
            "auto_advance" : true
        }
    }
}
```

And this is my user key mapping:
```json
[
    { "keys": ["super+ctrl+enter"], "command": "send_text_plus" },
    { "keys": ["super+\\"], "command": "send_text_plus_change_dir" }
]
```

**Comment by randy3k** [comment]
I think the settings are correct except, sendtextplus doesn't have any specialized support for ruby.
Did you see any error messages in the sublime console?

**Comment by NM-Clio** [comment]
In the past, I had somehow managed to get it working with iTerm but for some reason I had removed it. Now, after installing it again, I can't.

This appears in the console when I press the keyboard shortcut for SendTextPlus:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "sendtextplus in /Users/Nauman/Library/Application Support/Sublime Text 3/Installed Packages/SendTextPlus.sublime-package", line 16, in run
UnboundLocalError: local variable 'esel' referenced before assignment
```

**Comment by randy3k** [comment]
Sorry about it. It is fixed now.
